title: Angus Griffith
# email: your-email@example.com
description: >-
  I am a Mathematician and Programmer from Sydney Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sn6uv.github.io"
twitter_username: sn6uv
github_username:  sn6uv

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
